import type { AppNotification, CommentWithAuthor, Post, Profile } from "@/lib/types";

const base = (over: Partial<Profile>): Profile => ({
  id: "p0",
  username: "utente",
  full_name: "Utente",
  bio: null,
  profession: "altro",
  birth_date: null,
  phone: null,
  public_email: null,
  instagram: null,
  facebook: null,
  website: null,
  city: null,
  avatar_url: null,
  cover_url: null,
  is_admin: false,
  post_count: 0,
  follower_count: 0,
  following_count: 0,
  created_at: "2026-01-10T10:00:00Z",
  ...over,
});

export const DEMO_PROFILES: Profile[] = [
  base({
    id: "p0",
    username: "vincenzosilva",
    full_name: "Vincenzo Silva",
    profession: "altro",
    bio: "Direzione editoriale di ARTANTIS. Leggo tutto quello che viene proposto e decido cosa merita di stare nel feed.",
    city: "Roma",
    is_admin: true,
    post_count: 8,
    follower_count: 4210,
    following_count: 128,
    created_at: "2025-11-04T09:00:00Z",
  }),
  base({
    id: "p1",
    username: "elenavitali",
    full_name: "Elena Vitali",
    profession: "ricercatore",
    bio: "Biologa molecolare. Studio il rapporto fra microbiota intestinale e infiammazione cronica presso l'Università di Bologna.",
    city: "Bologna",
    public_email: "elena.vitali@esempio.it",
    instagram: "elena.vitali.lab",
    post_count: 34,
    follower_count: 1284,
    following_count: 96,
  }),
  base({
    id: "p2",
    username: "marcolanza",
    full_name: "Marco Lanza",
    profession: "medico",
    bio: "Cardiologo. Scrivo di prevenzione e di come leggere davvero i propri esami.",
    city: "Milano",
    post_count: 21,
    follower_count: 892,
    following_count: 140,
  }),
  base({
    id: "p3",
    username: "giuliaferri",
    full_name: "Giulia Ferri",
    profession: "pittore",
    bio: "Pittura a olio, ritratti e figure. Lavoro sulla luce delle stanze vuote.",
    city: "Firenze",
    post_count: 58,
    follower_count: 3120,
    following_count: 210,
  }),
  base({
    id: "p4",
    username: "saradonati",
    full_name: "Sara Donati",
    profession: "arte_e_benessere",
    bio: "Arteterapia e movimento consapevole. Conduco laboratori in ospedale.",
    city: "Torino",
    post_count: 12,
    follower_count: 447,
    following_count: 88,
  }),
  base({
    id: "p5",
    username: "pietroamato",
    full_name: "Pietro Amato",
    profession: "farmacista",
    bio: "Farmacia preparatoria. Racconto come nasce un galenico, passaggio per passaggio.",
    city: "Napoli",
    post_count: 17,
    follower_count: 615,
    following_count: 73,
  }),
  base({
    id: "p6",
    username: "nadiaricci",
    full_name: "Nadia Ricci",
    profession: "artista",
    bio: "Installazioni e materiali poveri. Il mio studio è un ex laboratorio tessile.",
    city: "Prato",
    post_count: 29,
    follower_count: 1740,
    following_count: 302,
  }),
];

/** Cerca per nome utente: così l'ordine dell'elenco può cambiare senza rompere nulla. */
const who = (username: string) => {
  const p = DEMO_PROFILES.find((x) => x.username === username) ?? DEMO_PROFILES[0];
  return {
    id: p.id,
    username: p.username,
    full_name: p.full_name,
    avatar_url: p.avatar_url,
    profession: p.profession,
  };
};

export const DEMO_POSTS: Post[] = [
  {
    id: "post1",
    author_id: "p1",
    title: "Quello che i nostri dati dicono davvero sul microbiota",
    content:
      "Abbiamo seguito 214 persone per diciotto mesi. La domanda era semplice: la composizione del microbiota intestinale cambia prima o dopo la comparsa dei marcatori infiammatori?\n\nLa risposta breve è: prima. Nei soggetti che hanno poi sviluppato un quadro infiammatorio, la diversità batterica iniziava a ridursi in media undici settimane prima che qualunque esame del sangue mostrasse un'alterazione.\n\nQuesto non significa che il microbiota causi l'infiammazione. Significa che potrebbe essere un segnale precoce, e che vale la pena studiarlo come tale. Nei prossimi mesi pubblicheremo il dataset completo.",
    category: "ricerca",
    status: "approved",
    rejection_reason: null,
    published_at: "2026-08-22T09:20:00Z",
    created_at: "2026-08-21T18:00:00Z",
    like_count: 342,
    comment_count: 28,
    repost_count: 61,
    author: who("elenavitali"),
    media: [],
  },
  {
    id: "post2",
    author_id: "p3",
    title: "Stanza con finestra a nord",
    content:
      "Tre mesi su una tela di un metro e venti. La luce del nord non cambia quasi mai durante il giorno: è la ragione per cui i pittori l'hanno sempre cercata, e la ragione per cui a un certo punto diventa insopportabile.\n\nHo dipinto la stessa parete undici volte prima di trovare il grigio giusto.",
    category: "opera",
    status: "approved",
    rejection_reason: null,
    published_at: "2026-08-21T16:40:00Z",
    created_at: "2026-08-21T16:00:00Z",
    like_count: 987,
    comment_count: 74,
    repost_count: 133,
    author: who("giuliaferri"),
    media: [
      { id: "m1", post_id: "post2", url: "/demo/opera-1.svg", media_type: "image", position: 0 },
      { id: "m2", post_id: "post2", url: "/demo/opera-2.svg", media_type: "image", position: 1 },
    ],
  },
  {
    id: "post3",
    author_id: "p2",
    title: "Come si legge un referto cardiologico senza spaventarsi",
    content:
      "Ogni settimana ricevo messaggi di persone terrorizzate da una sigla su un foglio. Facciamo ordine su tre voci che compaiono quasi sempre e che quasi sempre vengono fraintese.\n\n1. Frazione di eiezione. È la percentuale di sangue che il ventricolo sinistro espelle a ogni battito. Sopra il 50% si considera normale. Un 55% non è \"quasi malato\": è normale.\n\n2. Extrasistoli sporadiche. Il cuore di chiunque ne fa. Il numero conta più della presenza.\n\n3. Insufficienza valvolare lieve. La parola insufficienza suona grave, ma nella grande maggioranza dei referti descrive un reperto che non richiede nulla, se non un controllo nel tempo.",
    category: "divulgazione",
    status: "approved",
    rejection_reason: null,
    published_at: "2026-08-20T11:05:00Z",
    created_at: "2026-08-20T10:00:00Z",
    like_count: 1520,
    comment_count: 96,
    repost_count: 288,
    author: who("marcolanza"),
    media: [],
  },
  {
    id: "post4",
    author_id: "p5",
    content:
      "Un galenico non è una magia: è una bilancia di precisione, una scheda di lavorazione e la pazienza di rifare il calcolo due volte. Oggi una crema all'urea al 30% per una paziente con ipercheratosi. Trentotto minuti, tre firme, un contenitore etichettato a mano.",
    title: "",
    category: "processo creativo",
    status: "approved",
    rejection_reason: null,
    published_at: "2026-08-19T15:30:00Z",
    created_at: "2026-08-19T15:00:00Z",
    like_count: 214,
    comment_count: 12,
    repost_count: 19,
    author: who("pietroamato"),
    media: [
      { id: "m3", post_id: "post4", url: "/demo/opera-3.svg", media_type: "image", position: 0 },
    ],
  },
];

export const DEMO_PENDING: Post[] = [
  {
    ...DEMO_POSTS[0],
    id: "pending1",
    status: "pending",
    published_at: null,
    title: "Perché abbiamo rifatto lo studio da capo",
    content:
      "Il primo campione era sbilanciato: 68 partecipanti su 90 venivano dalla stessa area urbana. Ce ne siamo accorti al momento dell'analisi, non prima, e questo è già un errore nostro.\n\nAbbiamo rifatto il reclutamento su quattro province, allungando i tempi di otto mesi. I risultati che ne escono sono più deboli di quelli iniziali: l'effetto c'è ma è circa la metà.\n\nPubblico anche questo perché la parte che non funziona è quella da cui si impara.",
    category: "ricerca",
    media: [],
    like_count: 0,
    comment_count: 0,
    repost_count: 0,
    created_at: "2026-08-23T12:10:00Z",
  },
  {
    ...DEMO_POSTS[2],
    id: "pending2",
    status: "pending",
    published_at: null,
    title: "Il mito dei diecimila passi",
    content:
      "La cifra non viene da uno studio: viene da una campagna pubblicitaria giapponese del 1965 per un contapassi che si chiamava, letteralmente, \"misuratore dei diecimila passi\".\n\nQuesto non vuol dire che camminare non serva. Vuol dire che la soglia è arbitraria. I lavori più recenti trovano un beneficio già intorno ai quattromila passi al giorno.",
    category: "divulgazione",
    media: [],
    like_count: 0,
    comment_count: 0,
    repost_count: 0,
    created_at: "2026-08-23T17:30:00Z",
  },
  {
    ...DEMO_POSTS[1],
    id: "pending3",
    status: "pending",
    published_at: null,
    title: "Serie \"Interni\" — tre studi preparatori",
    content:
      "Vorrei proporre tre studi a carboncino realizzati prima della tela grande. Sono lavori di passaggio, non opere finite, ma raccontano meglio del quadro definitivo come si arriva a una composizione.\n\nIl terzo è quello in cui ho capito che la finestra andava spostata di quaranta centimetri.",
    category: "processo creativo",
    like_count: 0,
    comment_count: 0,
    repost_count: 0,
    created_at: "2026-08-23T22:40:00Z",
  },
  {
    ...DEMO_POSTS[0],
    id: "pending4",
    status: "pending",
    published_at: null,
    title: "Nuovo articolo in uscita",
    content: "A breve esce il nostro nuovo lavoro. Vi aggiorno appena posso.",
    category: "annuncio",
    media: [],
    like_count: 0,
    comment_count: 0,
    repost_count: 0,
    created_at: "2026-08-24T02:20:00Z",
  },
  {
    ...DEMO_POSTS[1],
    id: "pending5",
    status: "pending",
    published_at: null,
    title: "Laboratorio di ritratto dal vero — iscrizioni aperte",
    content:
      "Sei incontri di tre ore, il sabato mattina, nel mio studio a Prato. Massimo otto persone, modello dal vero a ogni incontro.\n\nNon serve esperienza precedente ma serve la voglia di sbagliare parecchio nelle prime due settimane.\n\nCosto e date nei commenti, oppure scrivetemi in privato.",
    category: "annuncio",
    media: [],
    like_count: 0,
    comment_count: 0,
    repost_count: 0,
    created_at: "2026-08-24T05:15:00Z",
  },
];

export const DEMO_COMMENTS: CommentWithAuthor[] = [
  {
    id: "c1",
    content:
      "Dato interessantissimo. Avete controllato l'effetto della dieta nelle undici settimane precedenti?",
    created_at: "2026-08-22T10:10:00Z",
    author_id: "p2",
    author: {
      id: "p2",
      username: "marcolanza",
      full_name: "Marco Lanza",
      avatar_url: null,
    },
  },
  {
    id: "c2",
    content: "Aspetto il dataset. Se lo pubblicate in formato aperto lo useremo per il corso.",
    created_at: "2026-08-22T12:44:00Z",
    author_id: "p6",
    author: {
      id: "p6",
      username: "nadiaricci",
      full_name: "Nadia Ricci",
      avatar_url: null,
    },
  },
];

export const DEMO_NOTIFICATIONS: AppNotification[] = [
  {
    id: "n1",
    type: "post_approved",
    read: false,
    created_at: "2026-08-24T07:40:00Z",
    post_id: "post2",
    actor: who("vincenzosilva"),
    post: { id: "post2", title: "Stanza con finestra a nord" },
  },
  {
    id: "n2",
    type: "like",
    read: false,
    created_at: "2026-08-24T06:10:00Z",
    post_id: "post1",
    actor: who("marcolanza"),
    post: { id: "post1", title: "Quello che i nostri dati dicono davvero sul microbiota" },
  },
  {
    id: "n3",
    type: "comment",
    read: false,
    created_at: "2026-08-24T04:25:00Z",
    post_id: "post1",
    actor: who("nadiaricci"),
    post: { id: "post1", title: "Quello che i nostri dati dicono davvero sul microbiota" },
  },
  {
    id: "n4",
    type: "follow",
    read: true,
    created_at: "2026-08-23T19:05:00Z",
    post_id: null,
    actor: who("saradonati"),
    post: null,
  },
  {
    id: "n5",
    type: "repost",
    read: true,
    created_at: "2026-08-23T12:30:00Z",
    post_id: "post3",
    actor: who("pietroamato"),
    post: { id: "post3", title: "Come si legge un referto cardiologico senza spaventarsi" },
  },
  {
    id: "n6",
    type: "post_rejected",
    read: true,
    created_at: "2026-08-22T16:00:00Z",
    post_id: "pending4",
    actor: who("vincenzosilva"),
    post: { id: "pending4", title: "Nuovo articolo in uscita" },
  },
];
