import type { CommentWithAuthor, Post, Profile } from "@/lib/types";

const base = (over: Partial<Profile>): Profile => ({
  id: "p0",
  username: "utente",
  full_name: "Utente",
  bio: null,
  profession: "altro",
  birth_date: null,
  phone: null,
  public_email: null,
  instagram: null,
  facebook: null,
  website: null,
  city: null,
  avatar_url: null,
  cover_url: null,
  is_admin: false,
  post_count: 0,
  follower_count: 0,
  following_count: 0,
  created_at: "2026-01-10T10:00:00Z",
  ...over,
});

export const DEMO_PROFILES: Profile[] = [
  base({
    id: "p0",
    username: "vincenzosilva",
    full_name: "Vincenzo Silva",
    profession: "altro",
    bio: "Direzione editoriale di ARTANTIS. Leggo tutto quello che viene proposto e decido cosa merita di stare nel feed.",
    city: "Roma",
    is_admin: true,
    post_count: 8,
    follower_count: 4210,
    following_count: 128,
    created_at: "2025-11-04T09:00:00Z",
  }),
  base({
    id: "p1",
    username: "elenavitali",
    full_name: "Elena Vitali",
    profession: "ricercatore",
    bio: "Biologa molecolare. Studio il rapporto fra microbiota intestinale e infiammazione cronica presso l'Università di Bologna.",
    city: "Bologna",
    public_email: "elena.vitali@esempio.it",
    instagram: "elena.vitali.lab",
    post_count: 34,
    follower_count: 1284,
    following_count: 96,
  }),
  base({
    id: "p2",
    username: "marcolanza",
    full_name: "Marco Lanza",
    profession: "medico",
    bio: "Cardiologo. Scrivo di prevenzione e di come leggere davvero i propri esami.",
    city: "Milano",
    post_count: 21,
    follower_count: 892,
    following_count: 140,
  }),
  base({
    id: "p3",
    username: "giuliaferri",
    full_name: "Giulia Ferri",
    profession: "pittore",
    bio: "Pittura a olio, ritratti e figure. Lavoro sulla luce delle stanze vuote.",
    city: "Firenze",
    post_count: 58,
    follower_count: 3120,
    following_count: 210,
  }),
  base({
    id: "p4",
    username: "saradonati",
    full_name: "Sara Donati",
    profession: "arte_e_benessere",
    bio: "Arteterapia e movimento consapevole. Conduco laboratori in ospedale.",
    city: "Torino",
    post_count: 12,
    follower_count: 447,
    following_count: 88,
  }),
  base({
    id: "p5",
    username: "pietroamato",
    full_name: "Pietro Amato",
    profession: "farmacista",
    bio: "Farmacia preparatoria. Racconto come nasce un galenico, passaggio per passaggio.",
    city: "Napoli",
    post_count: 17,
    follower_count: 615,
    following_count: 73,
  }),
  base({
    id: "p6",
    username: "nadiaricci",
    full_name: "Nadia Ricci",
    profession: "artista",
    bio: "Installazioni e materiali poveri. Il mio studio è un ex laboratorio tessile.",
    city: "Prato",
    post_count: 29,
    follower_count: 1740,
    following_count: 302,
  }),
];

/** Cerca per nome utente: così l'ordine dell'elenco può cambiare senza rompere nulla. */
const who = (username: string) => {
  const p = DEMO_PROFILES.find((x) => x.username === username) ?? DEMO_PROFILES[0];
  return {
    id: p.id,
    username: p.username,
    full_name: p.full_name,
    avatar_url: p.avatar_url,
    profession: p.profession,
  };
};

export const DEMO_POSTS: Post[] = [
  {
    id: "post1",
    author_id: "p1",
    title: "Quello che i nostri dati dicono davvero sul microbiota",
    content:
      "Abbiamo seguito 214 persone per diciotto mesi. La domanda era semplice: la composizione del microbiota intestinale cambia prima o dopo la comparsa dei marcatori infiammatori?\n\nLa risposta breve è: prima. Nei soggetti che hanno poi sviluppato un quadro infiammatorio, la diversità batterica iniziava a ridursi in media undici settimane prima che qualunque esame del sangue mostrasse un'alterazione.\n\nQuesto non significa che il microbiota causi l'infiammazione. Significa che potrebbe essere un segnale precoce, e che vale la pena studiarlo come tale. Nei prossimi mesi pubblicheremo il dataset completo.",
    category: "ricerca",
    status: "approved",
    rejection_reason: null,
    published_at: "2026-08-22T09:20:00Z",
    created_at: "2026-08-21T18:00:00Z",
    like_count: 342,
    comment_count: 28,
    repost_count: 61,
    author: who("elenavitali"),
    media: [],
  },
  {
    id: "post2",
    author_id: "p3",
    title: "Stanza con finestra a nord",
    content:
      "Tre mesi su una tela di un metro e venti. La luce del nord non cambia quasi mai durante il giorno: è la ragione per cui i pittori l'hanno sempre cercata, e la ragione per cui a un certo punto diventa insopportabile.\n\nHo dipinto la stessa parete undici volte prima di trovare il grigio giusto.",
    category: "opera",
    status: "approved",
    rejection_reason: null,
    published_at: "2026-08-21T16:40:00Z",
    created_at: "2026-08-21T16:00:00Z",
    like_count: 987,
    comment_count: 74,
    repost_count: 133,
    author: who("giuliaferri"),
    media: [
      { id: "m1", post_id: "post2", url: "/demo/opera-1.svg", media_type: "image", position: 0 },
      { id: "m2", post_id: "post2", url: "/demo/opera-2.svg", media_type: "image", position: 1 },
    ],
  },
  {
    id: "post3",
    author_id: "p2",
    title: "Come si legge un referto cardiologico senza spaventarsi",
    content:
      "Ogni settimana ricevo messaggi di persone terrorizzate da una sigla su un foglio. Facciamo ordine su tre voci che compaiono quasi sempre e che quasi sempre vengono fraintese.\n\n1. Frazione di eiezione. È la percentuale di sangue che il ventricolo sinistro espelle a ogni battito. Sopra il 50% si considera normale. Un 55% non è \"quasi malato\": è normale.\n\n2. Extrasistoli sporadiche. Il cuore di chiunque ne fa. Il numero conta più della presenza.\n\n3. Insufficienza valvolare lieve. La parola insufficienza suona grave, ma nella grande maggioranza dei referti descrive un reperto che non richiede nulla, se non un controllo nel tempo.",
    category: "divulgazione",
    status: "approved",
    rejection_reason: null,
    published_at: "2026-08-20T11:05:00Z",
    created_at: "2026-08-20T10:00:00Z",
    like_count: 1520,
    comment_count: 96,
    repost_count: 288,
    author: who("marcolanza"),
    media: [],
  },
  {
    id: "post4",
    author_id: "p5",
    content:
      "Un galenico non è una magia: è una bilancia di precisione, una scheda di lavorazione e la pazienza di rifare il calcolo due volte. Oggi una crema all'urea al 30% per una paziente con ipercheratosi. Trentotto minuti, tre firme, un contenitore etichettato a mano.",
    title: "",
    category: "processo creativo",
    status: "approved",
    rejection_reason: null,
    published_at: "2026-08-19T15:30:00Z",
    created_at: "2026-08-19T15:00:00Z",
    like_count: 214,
    comment_count: 12,
    repost_count: 19,
    author: who("pietroamato"),
    media: [
      { id: "m3", post_id: "post4", url: "/demo/opera-3.svg", media_type: "image", position: 0 },
    ],
  },
];

export const DEMO_PENDING: Post[] = [
  {
    ...DEMO_POSTS[1],
    id: "pending1",
    status: "pending",
    published_at: null,
    title: "Serie \"Interni\" — tre studi preparatori",
    content:
      "Vorrei proporre tre studi a carboncino realizzati prima della tela grande. Sono lavori di passaggio, ma raccontano meglio del quadro finito come si arriva a una composizione.",
    like_count: 0,
    comment_count: 0,
    repost_count: 0,
    created_at: "2026-08-23T07:40:00Z",
  },
  {
    ...DEMO_POSTS[3],
    id: "pending2",
    status: "pending",
    published_at: null,
    title: "Preparazioni magistrali: cosa può e cosa non può fare una farmacia",
    content:
      "Un chiarimento necessario, perché le richieste che ricevo al banco sono spesso fuori da ciò che la legge consente. Elenco i casi più frequenti e cosa si può proporre in alternativa.",
    media: [],
    like_count: 0,
    comment_count: 0,
    repost_count: 0,
    created_at: "2026-08-23T06:10:00Z",
  },
];

export const DEMO_COMMENTS: CommentWithAuthor[] = [
  {
    id: "c1",
    content:
      "Dato interessantissimo. Avete controllato l'effetto della dieta nelle undici settimane precedenti?",
    created_at: "2026-08-22T10:10:00Z",
    author_id: "p2",
    author: {
      id: "p2",
      username: "marcolanza",
      full_name: "Marco Lanza",
      avatar_url: null,
    },
  },
  {
    id: "c2",
    content: "Aspetto il dataset. Se lo pubblicate in formato aperto lo useremo per il corso.",
    created_at: "2026-08-22T12:44:00Z",
    author_id: "p6",
    author: {
      id: "p6",
      username: "nadiaricci",
      full_name: "Nadia Ricci",
      avatar_url: null,
    },
  },
];
